import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = "plotly_white"


def eda(df):
    st.title("General Information About the Data")
    st.write("# Data Overview")
    st.write(df.head())

    st.write("### Descriptive Statistics")
    st.write(df.describe())

    fig = px.scatter(df, 
                 x='Price', 
                 y='Revenue generated', 
                 color='Product type', 
                 hover_data=['Number of products sold'], 
                 trendline="ols")
    st.plotly_chart(fig)  


    # Pie chart for sales by product type
    sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()
    pie_chart = px.pie(sales_data, 
                    values='Number of products sold', 
                    names='Product type', 
                    title='Sales by Product Type', 
                    hover_data=['Number of products sold'],
                    hole=0.5,
                    color_discrete_sequence=px.colors.qualitative.Pastel)
    pie_chart.update_traces(textposition='inside', textinfo='percent+label')
    st.plotly_chart(pie_chart)

    # Bar chart for total revenue by shipping carrier
    total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
    bar_fig = go.Figure()
    bar_fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'], 
                            y=total_revenue['Revenue generated']))
    bar_fig.update_layout(title='Total Revenue by Shipping Carrier', 
                        xaxis_title='Shipping Carrier', 
                        yaxis_title='Revenue Generated')
    st.plotly_chart(bar_fig)

    # Average lead time and manufacturing costs
    avg_lead_time = df.groupby('Product type')['Lead time'].mean().reset_index()
    avg_manufacturing_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
    result = pd.merge(avg_lead_time, avg_manufacturing_costs, on='Product type')
    result.rename(columns={'Lead time': 'Average Lead Time', 
                        'Manufacturing costs': 'Average Manufacturing Costs'}, 
                inplace=True)

    # Display average lead time and manufacturing costs as a table
    st.header("Average Lead Time and Manufacturing Costs by Product Type")
    st.dataframe(result)

    # Line chart for revenue generated by SKU
    revenue_chart = px.line(df, 
                            x='SKU', 
                            y='Revenue generated', 
                            title='Revenue Generated by SKU')
    st.plotly_chart(revenue_chart)

    # Stock Levels
    st.header("5. Stock Levels Analysis")
    st.write("Stock levels refer to the number of products a store or business has in its inventory. Now let’s have a look at the stock levels of each SKU:")
    stock_chart = px.line(df, x='SKU', 
                        y='Stock levels', 
                        title='Stock Levels by SKU')
    st.plotly_chart(stock_chart)

    # Order Quantity Analysis
    st.header("6. Order Quantity Analysis")
    st.write("Now let’s have a look at the order quantity of each SKU:")
    order_quantity_chart = px.bar(df, x='SKU', 
                                y='Order quantities', 
                                title='Order Quantity by SKU')
    st.plotly_chart(order_quantity_chart)

    # Shipping Cost Analysis
    st.header("7. Shipping Cost Analysis")
    st.write("Now let’s analyze the shipping cost of carriers:")
    shipping_cost_chart = px.bar(df, x='Shipping carriers', 
                                y='Shipping costs', 
                                title='Shipping Costs by Carrier')
    st.plotly_chart(shipping_cost_chart)

    # Cost Distribution by Transportation Mode
    st.header("8. Cost Distribution by Transportation Mode")
    st.write("We discovered that Carrier B helps the company in more revenue. It is also the most costly Carrier among the three. Now let’s have a look at the cost distribution by transportation mode:")
    transportation_chart = px.pie(df, 
                                values='Costs', 
                                names='Transportation modes', 
                                title='Cost Distribution by Transportation Mode',
                                hole=0.5,
                                color_discrete_sequence=px.colors.qualitative.Pastel)
    st.plotly_chart(transportation_chart)

    # Analyzing Defect Rate
    st.header("9. Analyzing Defect Rate")
    st.write("The defect rate in the supply chain refers to the percentage of products that have something wrong or are found broken after shipping. Let’s have a look at the average defect rate of all product types:")
    defect_rates_by_product = df.groupby('Product type')['Defect rates'].mean().reset_index()
    defect_rate_chart = px.bar(defect_rates_by_product, x='Product type', y='Defect rates',
                                title='Average Defect Rates by Product Type')
    st.plotly_chart(defect_rate_chart)

    # Defect Rates by Mode of Transportation
    st.write("Now let’s have a look at the defect rates by mode of transportation:")
    pivot_table = pd.pivot_table(df, values='Defect rates', 
                                index=['Transportation modes'], 
                                aggfunc='mean')

    transportation_defect_chart = px.pie(values=pivot_table["Defect rates"], 
                                        names=pivot_table.index, 
                                        title='Defect Rates by Transportation Mode',
                                        hole=0.5,
                                        color_discrete_sequence=px.colors.qualitative.Pastel)
    st.plotly_chart(transportation_defect_chart)